FROM php:8.3.3-fpm-alpine

RUN apk update && apk upgrade

HEALTHCHECK --timeout=3s \
    CMD ps | awk '{ print ($4 == "crond" && $5 == "-f") ? 0 : 1 }' | grep 0 || exit 1

ENV COMMAND='php /www/artisan schedule:run'
ENV OUTPUT='/dev/stdout'

RUN echo '* * * * *' $COMMAND '>>' $OUTPUT '2>&1' > /etc/crontabs/root

CMD ["crond", "-f"]